spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 8338
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    #    defer-datasource-initialization: true ???? ??? data.sql? ??? ???? ????? ???? sql? ??????
    defer-datasource-initialization: true
    database-platform: mariadb
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

