spring:

  datasource:
    username: root
    password: 8338

    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop
  jpa:
    #    defer-datasource-initialization: true ???? ??? data.sql? ??? ???? ????? ???? sql? ??????
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: "ZGF5b25lLXNwcmluZz1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK"